l_gripper_state_separator:
  joint_names:
    - left_gripper_base_joint_gripper_left
    - left_gripper_base_joint_gripper_right
l_gripper_pos_controller:
  vel_command_type: MultiJointVelocityCommand
  max_speed: 1.2
  p_gain: 3.5
