r_arm_vel:
  type: "iai_robot_mechanism_controllers/MultiJointVelocityImpedanceController"
  joints:
    - right_arm_0_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
  gains:
    right_arm_0_joint: {p: 4, d: 0.0}
    right_arm_1_joint: {p: 4, d: 0.0}
    right_arm_2_joint: {p: 4, d: 0.0}
    right_arm_3_joint: {p: 4, d: 0.0}
    right_arm_4_joint: {p: 4, d: 0.0}
    right_arm_5_joint: {p: 4, d: 0.0}
    right_arm_6_joint: {p: 4, d: 0.0}


l_arm_vel:
  type: "iai_robot_mechanism_controllers/MultiJointVelocityImpedanceController"
  joints:
    - left_arm_0_joint
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
  gains:
    left_arm_0_joint: {p: 4.0, d: 0.0}
    left_arm_1_joint: {p: 4.0, d: 0.0}
    left_arm_2_joint: {p: 4.0, d: 0.0}
    left_arm_3_joint: {p: 4.0, d: 0.0}
    left_arm_4_joint: {p: 4.0, d: 0.0}
    left_arm_5_joint: {p: 4.0, d: 0.0}
    left_arm_6_joint: {p: 4.0, d: 0.0}

head_pan_vel:
  type: robot_mechanism_controllers/JointVelocityController
  joint: head_pan_joint
  pid:
    p: 4.0
    i: 0
    d: 0
    i_clamp: 0

head_tilt_vel:
  type: robot_mechanism_controllers/JointVelocityController
  joint: head_tilt_joint
  pid:
    p: 4.0
    i: 0
    d: 0
    i_clamp: 0

triangle_base_vel:
  type: robot_mechanism_controllers/JointVelocityController
  joint: triangle_base_joint
  pid:
    p: 4.0
    i: 0
    d: 0
    i_clamp: 0
